### ISSUE TITLE
ssb-links crashes sbot

### ISSUE THREAD

**Issue by elsehow** [ssbc/ssb-links#2]
Following the setup instructions for patchbay, I installed the required plugins. Now, after `sbot server`, I get an error that points here, stacktrace below. Any ideas?

node -v v6.9.0

```sh
/Users/ffff/.ssb/node_modules/ssb-links/index.js:29
  var s = ssb._flumeUse('links2', FlumeQueryLinks(indexes, extractLinks, 1))
              ^

TypeError: ssb._flumeUse is not a function
    at Object.exports.init (/Users/ffff/.ssb/node_modules/ssb-links/index.js:29:15)
    at /Users/ffff/.nvm/versions/node/v6.9.0/lib/node_modules/scuttlebot/node_modules/secret-stack/api.js:27:28
    at Array.forEach (native)
    at create (/Users/ffff/.nvm/versions/node/v6.9.0/lib/node_modules/scuttlebot/node_modules/secret-stack/api.js:26:20)
    at E0QooQWw4JTKwCN+ktTBoQjuTpNe3+kg8bk+DUY0yGw= (/Users/ffff/.nvm/versions/node/v6.9.0/lib/node_modules/scuttlebot/sbot.js:22343:16)
    at load (/Users/ffff/.nvm/versions/node/v6.9.0/lib/node_modules/scuttlebot/sbot.js:11:26)
    at prelude (/Users/ffff/.nvm/versions/node/v6.9.0/lib/node_modules/scuttlebot/sbot.js:23:10)
    at Object.<anonymous> (/Users/ffff/.nvm/versions/node/v6.9.0/lib/node_modules/scuttlebot/sbot.js:24:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by elsehow** [comment]
I fixed this by installing

```
sbot plugins.install ssb-query@0.1.2
sbot plugins.install ssb-links@2
sbot plugins.install ssb-ws
```

**Comment by dominictarr** [comment]
i have changed the latest to those versions so this should work okay now
