### ISSUE TITLE
sbot refuses to start after installing ssb-links

### ISSUE THREAD

**Issue by eb4890** [ssbc/ssb-links#6]
I'm getting the error

```
nvm/versions/node/v8.12.0/lib/node_modules/scuttlebot/plugins/plugins.js:187
        throw new Error('plugin at:'+module_name+' expected name:'+name+' but had:'+(plugin||{}).name)
        ^

Error: plugin at:ssb-links expected name:links but had:links2
    at Object.module.exports.loadUserPlugins /versions/node/v8.12.0/lib/node_modules/scuttlebot/plugins/plugins.js:187:15)
    at Object.<anonymous> 
/nvm/versions/node/v8.12.0/lib/node_modules/scuttlebot/bin.js:56:32)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```
Scuttlebot version

```
~/.nvm/versions/node/v8.12.0/lib/node_modules/scuttlebot/node_modules$ npm list -g scuttlebot
/home/eb4890/.nvm/versions/node/v8.12.0/lib
└── scuttlebot@12.2.3 
```

Should that plugin checking be reverted or should this plugin be forked?

**Comment by cryptix** [comment]
How do you construct your sbot? That plugin is already available by [default](https://github.com/ssbc/scuttlebot/blob/99f266c9c28ac47f077474a5af847171a38f9c18/bin.js#L52).

**Comment by cryptix** [comment]
Okay, sorry for the confusion. i'm not sure why `ssb-plugins` is installed in 2b.

`npm install scuttlebot` or `npm i && npm start` from it's source should give you that plugin. You can query the available api functions with `sbot manifest` once it is running.

**Comment by eb4890** [comment]
Thanks. I'll create a PR on the documentation to say you don't need to install it.
