### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-links#7]
I'm trying to try out git-ssb, so I'm trying to install ssb-npm, which involves running sbot with ssb-npm-registry, but when I do that it complains that:

```
/home/christianbundy/.ssb/node_modules/ssb-npm-registry/index.js:359
  if (!this.links2) throw new Error('missing ssb-links2 scuttlebot plugin')
                    ^

Error: missing ssb-links2 scuttlebot plugin
    at new SsbNpmRegistryServer (/home/christianbundy/.ssb/node_modules/ssb-npm-registry/index.js:359:27)
    at Object.exports.respond (/home/christianbundy/.ssb/node_modules/ssb-npm-registry/index.js:148:13)
    at Object.exports.init (/home/christianbundy/.ssb/node_modules/ssb-npm-registry/index.js:118:42)
    at /home/christianbundy/src/ssbc/scuttlebot/node_modules/secret-stack/api.js:43:28
    at Array.forEach (<anonymous>)
    at create (/home/christianbundy/src/ssbc/scuttlebot/node_modules/secret-stack/api.js:42:20)
    at Object.<anonymous> (/home/christianbundy/src/ssbc/scuttlebot/bin.js:70:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

When I install and enable ssb-links, it now throws:

```
/home/christianbundy/src/ssbc/scuttlebot/plugins/plugins.js:198
        throw new Error('plugin at:'+module_name+' expected name:'+name+' but had:'+(plugin||{}).name)
        ^

Error: plugin at:ssb-links expected name:links but had:links2
    at Object.module.exports.loadUserPlugins (/home/christianbundy/src/ssbc/scuttlebot/plugins/plugins.js:198:15)
    at Object.<anonymous> (/home/christianbundy/src/ssbc/scuttlebot/bin.js:58:32)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

cc: @clehner (because git-ssb-npm-registry) @arj03 (I think you deprecated ssb-links in sbot?)

**Comment by cryptix** [comment]
hmm.. my quick-fix suggestion would be to rename the folder and config entry to `ssb-links2`. Long term I think we should rename the repo?

ps: The prefix strip and name assertion is here: https://github.com/ssbc/scuttlebot/blob/648624dc662bb49f03401298ab70bed0e2f31a52/plugins/plugins.js#L198

pps: I guess you know this but it's still loaded unless you use `--disable-ssb-links`, right? https://github.com/ssbc/scuttlebot/blob/648624dc662bb49f03401298ab70bed0e2f31a52/bin.js#L63

**Comment by christianbundy** [comment]
Is there an active ssb-links? Sorry, I don't think I understand the history of ssb-links[2] or its deprecation. I didn't see any documentation about that command-line flag, so I'm just using normal `sbot server`.

**Comment by arj03** [comment]
@christianbundy https://github.com/ssbc/scuttlebot/releases

**Comment by christianbundy** [comment]
Thanks @arj03, I didn't think to look there but I should've.

Would it be best to rename this to ssb-links2, or have dependencies refer to it as ssb-links?

**Comment by austinfrey** [comment]
one thing to note when using ssb-npm-registry is that the order of the listed plugins is important. 

this works
```json
plugins: {
  "ssb-links": "links2",
  "ssb-npm-registry": true
}
```

this does not
```json
plugins: {
  "ssb-npm-registry": true,
  "ssb-links": "links2"
}
```

**Comment by HendrikPetertje** [comment]
Not really though. Just did a fresh install. when running 

```
▶sbot plugins.install ssb-links

```

The installation goes well, when then however restarting sbot (using sbot start) the following error is thrown:

▶ sbot start
ssb-server 14.1.12 /Users/******/.ssb logging.level:notice
my key ID: ***************************
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'flumeview-query/links'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/*****/.ssb/node_modules/ssb-links/index.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
```

My config:

```
{
  "plugins": {
    "ssb-links": "links2",
  }
}
```

Changing to:

```
{
  "plugins": {
    "ssb-links": true,
  }
}
```

Yields the same results. I'm running node `v11.15.0`

Folder structure with links sitting in the right folders:
<img width="234" alt="Screenshot 2019-05-04 at 22 00 51" src="https://user-images.githubusercontent.com/3583395/57184199-224cb100-6eb8-11e9-8935-8c2876928a9e.png">
(I've dissabled ssb-npm-registry from config to get rid of that noise since it wont work untill links2 is running anyway)

Any Idea what I'm doing wrong?

**Comment by HendrikPetertje** [comment]
extra context I'm running `ssb-server 14.1.12`

**Comment by christianbundy** [comment]
@HendrikPetertje Do you mind opening a new issue for your bug? It doesn't look like you're having the same "Error: missing ssb-links2 scuttlebot plugin" problem and I don't want your bug report to get lost when this issue closes.

**Comment by HendrikPetertje** [comment]
https://github.com/ssbc/ssb-links/pull/9 
opened a pull request instead. thanks for the reply!
